apiVersion: v1
kind: Secret
metadata:
  name: noteflow-shared-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noteflow-services.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.global.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.global.minio.secretKey | quote }}
