upstream user_service {
    server user-service:8001;
}

upstream note_service {
    server note-service:8002;
}

upstream file_service {
    server file-service:8003;
}

server {
    listen 80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # user-service
    location /auth/ {
        proxy_pass http://user_service;
    }

    location /users/ {
        proxy_pass http://user_service;
    }

    location /health/user {
        proxy_pass http://user_service/health;
    }

    # note-service
    location /notes/ {
        proxy_pass http://note_service;
    }

    location /tags/ {
        proxy_pass http://note_service;
    }

    location /search {
        proxy_pass http://note_service;
    }

    location /health/note {
        proxy_pass http://note_service/health;
    }

    # file-service
    location /files/ {
        proxy_pass http://file_service;
        client_max_body_size 100m;
    }

    location /health/file {
        proxy_pass http://file_service/health;
    }
}
