apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-haproxy-config
  namespace: edge
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 4096

    defaults
      mode http
      log global
      option httplog
      option forwardfor
      timeout connect 5s
      timeout client 60s
      timeout server 60s

    frontend http-in
      bind *:8080
      http-request set-header X-Forwarded-Proto http
      default_backend istio_ingress

    backend istio_ingress
      balance roundrobin
      option httpchk
      http-check connect port 15021
      http-check send meth GET uri /healthz/ready ver HTTP/1.1 hdr Host istio-ingressgateway.istio-ingress.svc.cluster.local
      http-check expect status 200
      server istio-gateway istio-ingressgateway.istio-ingress.svc.cluster.local:80 check
