apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IlmirSharifullin/note-flow
    targetRevision: HEAD
    path: infra/gitops/platform/local-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
