apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: rate-limit
  labels:
    app.kubernetes.io/name: ratelimit
    app.kubernetes.io/part-of: ingress
spec:
  selector:
    app.kubernetes.io/name: ratelimit
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 8081
      targetPort: grpc
